2017-01-19T08:35:00.272Z - error: uncaughtException: connection timeout date=Thu Jan 19 2017 14:05:00 GMT+0530 (IST), pid=18709, uid=501, gid=20, cwd=/Users/anshulsharma/Desktop/chibleetestbackend, execPath=/usr/local/bin/node, version=v4.4.7, argv=[/usr/local/bin/node, /Users/anshulsharma/Desktop/chibleetestbackend/server.js], rss=50192384, heapTotal=76126304, heapUsed=74575728, loadavg=[2.13232421875, 1.96044921875, 1.86767578125], uptime=679731
Error: connection timeout
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:168:17)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at listener (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/node_modules/mongodb/lib/db.js:1791:14)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/node_modules/mongodb/lib/server.js:270:14)
    at g (events.js:260:16)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb-core/lib/topologies/server.js:322:12)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb-core/lib/connection/pool.js:271:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb-core/lib/connection/connection.js:175:10)
    at Socket.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)
    at Socket._onTimeout (net.js:332:8)
    at _runOnTimeout (timers.js:524:11)
    at _makeTimerTimeout (timers.js:515:3)
    at Timer.unrefTimeout (timers.js:584:5)
2017-01-25T10:36:04.260Z - info: 127.0.0.1 - - [25/Jan/2017:10:36:04 +0000] "PUT /v2/login HTTP/1.1" 200 - "-" "PostmanRuntime/3.0.9"

2017-01-25T10:38:28.942Z - info: 127.0.0.1 - - [25/Jan/2017:10:38:28 +0000] "PUT /v2/login HTTP/1.1" 200 - "-" "PostmanRuntime/3.0.9"

2017-01-25T10:39:02.731Z - info: 127.0.0.1 - - [25/Jan/2017:10:39:02 +0000] "PUT /v2/login HTTP/1.1" 200 - "-" "PostmanRuntime/3.0.9"

2017-01-25T10:43:06.726Z - error: uncaughtException: Unexpected token else date=Wed Jan 25 2017 16:13:06 GMT+0530 (IST), pid=57523, uid=501, gid=20, cwd=/Users/anshulsharma/Desktop/chibleetestbackend, execPath=/usr/local/bin/node, version=v4.4.7, argv=[/usr/local/bin/node, /Users/anshulsharma/Desktop/chibleetestbackend/server.js], rss=125820928, heapTotal=94696544, heapUsed=72838304, loadavg=[1.9453125, 2.06689453125, 2.0537109375], uptime=1205844
SyntaxError: Unexpected token else
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/modules/vendorapp/server/routes/vendorapp.server.routes.js:8:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /Users/anshulsharma/Desktop/chibleetestbackend/config/lib/express.js:275:9
    at Array.forEach (native)
    at Object.module.exports.initModulesServerRoutes (/Users/anshulsharma/Desktop/chibleetestbackend/config/lib/express.js:274:32)
    at Object.module.exports.init (/Users/anshulsharma/Desktop/chibleetestbackend/config/lib/express.js:340:10)
    at /Users/anshulsharma/Desktop/chibleetestbackend/config/lib/app.js:46:27
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongodb/lib/mongo_client.js:210:11
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
2017-01-25T10:44:13.335Z - error: uncaughtException: data1 is not defined date=Wed Jan 25 2017 16:14:13 GMT+0530 (IST), pid=57544, uid=501, gid=20, cwd=/Users/anshulsharma/Desktop/chibleetestbackend, execPath=/usr/local/bin/node, version=v4.4.7, argv=[/usr/local/bin/node, /Users/anshulsharma/Desktop/chibleetestbackend/server.js], rss=137691136, heapTotal=104991840, heapUsed=85769040, loadavg=[2.31298828125, 2.13037109375, 2.07666015625], uptime=1205911
ReferenceError: data1 is not defined
    at /Users/anshulsharma/Desktop/chibleetestbackend/modules/vendorapp/server/controllers/vendorapp.server.controller.js:447:19
    at Query.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/lib/model.js:3369:16)
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/kareem/index.js:259:21
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
2017-01-25T10:44:49.192Z - error: uncaughtException: vendor.updateOne is not a function date=Wed Jan 25 2017 16:14:49 GMT+0530 (IST), pid=57585, uid=501, gid=20, cwd=/Users/anshulsharma/Desktop/chibleetestbackend, execPath=/usr/local/bin/node, version=v4.4.7, argv=[/usr/local/bin/node, /Users/anshulsharma/Desktop/chibleetestbackend/server.js], rss=139108352, heapTotal=106023776, heapUsed=82133080, loadavg=[2.52880859375, 2.1953125, 2.1015625], uptime=1205947
TypeError: vendor.updateOne is not a function
    at /Users/anshulsharma/Desktop/chibleetestbackend/modules/vendorapp/server/controllers/vendorapp.server.controller.js:450:14
    at Query.<anonymous> (/Users/anshulsharma/Desktop/chibleetestbackend/node_modules/mongoose/lib/model.js:3369:16)
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/kareem/index.js:259:21
    at /Users/anshulsharma/Desktop/chibleetestbackend/node_modules/kareem/index.js:127:16
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
2017-01-25T10:45:12.926Z - info: 127.0.0.1 - - [25/Jan/2017:10:45:12 +0000] "PUT /v2/login HTTP/1.1" 200 - "-" "PostmanRuntime/3.0.9"

